name: "Lint"
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: hadolint
        uses: reviewdog/action-hadolint@v1
